# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/PB3284.xdc

# Block Designs: bd/MarsZX2/MarsZX2.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX2 || ORIG_REF_NAME==MarsZX2} -quiet] -quiet

# IP: bd/MarsZX2/ip/MarsZX2_axi_interconnect_0_0/MarsZX2_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX2_axi_interconnect_0_0 || ORIG_REF_NAME==MarsZX2_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/MarsZX2/ip/MarsZX2_axi_interconnect_1_0/MarsZX2_axi_interconnect_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX2_axi_interconnect_1_0 || ORIG_REF_NAME==MarsZX2_axi_interconnect_1_0} -quiet] -quiet

# IP: bd/MarsZX2/ip/MarsZX2_v_tc_0_0/MarsZX2_v_tc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX2_v_tc_0_0 || ORIG_REF_NAME==MarsZX2_v_tc_0_0} -quiet] -quiet

# IP: bd/MarsZX2/ip/MarsZX2_SysId_0_0_2/MarsZX2_SysId_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX2_SysId_0_0 || ORIG_REF_NAME==MarsZX2_SysId_0_0} -quiet] -quiet

# IP: bd/MarsZX2/ip/MarsZX2_Video_IO_2_HDMI_TMDS_0_0_2/MarsZX2_Video_IO_2_HDMI_TMDS_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX2_Video_IO_2_HDMI_TMDS_0_0 || ORIG_REF_NAME==MarsZX2_Video_IO_2_HDMI_TMDS_0_0} -quiet] -quiet

# IP: bd/MarsZX2/ip/MarsZX2_xbar_0_2/MarsZX2_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX2_xbar_0 || ORIG_REF_NAME==MarsZX2_xbar_0} -quiet] -quiet

# IP: bd/MarsZX2/ip/MarsZX2_axi_vdma_0_0_2/MarsZX2_axi_vdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX2_axi_vdma_0_0 || ORIG_REF_NAME==MarsZX2_axi_vdma_0_0} -quiet] -quiet

# IP: bd/MarsZX2/ip/MarsZX2_axis_fb_conv_0_0_2/MarsZX2_axis_fb_conv_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX2_axis_fb_conv_0_0 || ORIG_REF_NAME==MarsZX2_axis_fb_conv_0_0} -quiet] -quiet

# IP: bd/MarsZX2/ip/MarsZX2_clk_wiz_0_0/MarsZX2_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX2_clk_wiz_0_0 || ORIG_REF_NAME==MarsZX2_clk_wiz_0_0} -quiet] -quiet

# IP: bd/MarsZX2/ip/MarsZX2_clk_wiz_1_0/MarsZX2_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX2_clk_wiz_1_0 || ORIG_REF_NAME==MarsZX2_clk_wiz_1_0} -quiet] -quiet

# IP: bd/MarsZX2/ip/MarsZX2_proc_sys_reset_0_0_2/MarsZX2_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX2_proc_sys_reset_0_0 || ORIG_REF_NAME==MarsZX2_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/MarsZX2/ip/MarsZX2_processing_system7_0_0_2/MarsZX2_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX2_processing_system7_0_0 || ORIG_REF_NAME==MarsZX2_processing_system7_0_0} -quiet] -quiet

# IP: bd/MarsZX2/ip/MarsZX2_v_axi4s_vid_out_0_0_2/MarsZX2_v_axi4s_vid_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX2_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==MarsZX2_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: bd/MarsZX2/ip/MarsZX2_v_tc_0_0_2/MarsZX2_v_tc_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX2_v_tc_0_0 || ORIG_REF_NAME==MarsZX2_v_tc_0_0} -quiet] -quiet

# IP: bd/MarsZX2/ip/MarsZX2_xlconcat_0_0_2/MarsZX2_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX2_xlconcat_0_0 || ORIG_REF_NAME==MarsZX2_xlconcat_0_0} -quiet] -quiet

# IP: bd/MarsZX2/ip/MarsZX2_xlconstant0_1_0_2/MarsZX2_xlconstant0_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX2_xlconstant0_1_0 || ORIG_REF_NAME==MarsZX2_xlconstant0_1_0} -quiet] -quiet

# IP: bd/MarsZX2/ip/MarsZX2_hwclock_0_0_2/MarsZX2_hwclock_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX2_hwclock_0_0 || ORIG_REF_NAME==MarsZX2_hwclock_0_0} -quiet] -quiet

# IP: bd/MarsZX2/ip/MarsZX2_ltc2358_0_0_2/MarsZX2_ltc2358_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX2_ltc2358_0_0 || ORIG_REF_NAME==MarsZX2_ltc2358_0_0} -quiet] -quiet

# IP: bd/MarsZX2/ip/MarsZX2_csm_sim_0_0_2/MarsZX2_csm_sim_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX2_csm_sim_0_0 || ORIG_REF_NAME==MarsZX2_csm_sim_0_0} -quiet] -quiet

# IP: bd/MarsZX2/ip/MarsZX2_lld_load_0_0_2/MarsZX2_lld_load_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX2_lld_load_0_0 || ORIG_REF_NAME==MarsZX2_lld_load_0_0} -quiet] -quiet

# IP: bd/MarsZX2/ip/MarsZX2_clk_wiz_0_0_1/MarsZX2_clk_wiz_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX2_clk_wiz_0_0 || ORIG_REF_NAME==MarsZX2_clk_wiz_0_0} -quiet] -quiet

# IP: bd/MarsZX2/ip/MarsZX2_v_tc_0_0_1/MarsZX2_v_tc_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX2_v_tc_0_0 || ORIG_REF_NAME==MarsZX2_v_tc_0_0} -quiet] -quiet

# IP: bd/MarsZX2/ip/MarsZX2_fan_pwm_0_0/MarsZX2_fan_pwm_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX2_fan_pwm_0_0 || ORIG_REF_NAME==MarsZX2_fan_pwm_0_0} -quiet] -quiet

# IP: bd/MarsZX2/ip/MarsZX2_auto_pc_0_2/MarsZX2_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX2_auto_pc_0 || ORIG_REF_NAME==MarsZX2_auto_pc_0} -quiet] -quiet

# IP: bd/MarsZX2/ip/MarsZX2_auto_pc_9/MarsZX2_auto_pc_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX2_auto_pc_9 || ORIG_REF_NAME==MarsZX2_auto_pc_9} -quiet] -quiet

# IP: bd/MarsZX2/ip/MarsZX2_auto_pc_1_2/MarsZX2_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX2_auto_pc_1 || ORIG_REF_NAME==MarsZX2_auto_pc_1} -quiet] -quiet

# IP: bd/MarsZX2/ip/MarsZX2_auto_pc_2_2/MarsZX2_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX2_auto_pc_2 || ORIG_REF_NAME==MarsZX2_auto_pc_2} -quiet] -quiet

# IP: bd/MarsZX2/ip/MarsZX2_auto_pc_3_2/MarsZX2_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX2_auto_pc_3 || ORIG_REF_NAME==MarsZX2_auto_pc_3} -quiet] -quiet

# IP: bd/MarsZX2/ip/MarsZX2_auto_pc_4_2/MarsZX2_auto_pc_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX2_auto_pc_4 || ORIG_REF_NAME==MarsZX2_auto_pc_4} -quiet] -quiet

# IP: bd/MarsZX2/ip/MarsZX2_auto_pc_5_2/MarsZX2_auto_pc_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX2_auto_pc_5 || ORIG_REF_NAME==MarsZX2_auto_pc_5} -quiet] -quiet

# IP: bd/MarsZX2/ip/MarsZX2_auto_pc_6_2/MarsZX2_auto_pc_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX2_auto_pc_6 || ORIG_REF_NAME==MarsZX2_auto_pc_6} -quiet] -quiet

# IP: bd/MarsZX2/ip/MarsZX2_auto_pc_7_2/MarsZX2_auto_pc_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX2_auto_pc_7 || ORIG_REF_NAME==MarsZX2_auto_pc_7} -quiet] -quiet

# IP: bd/MarsZX2/ip/MarsZX2_auto_pc_8_2/MarsZX2_auto_pc_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX2_auto_pc_8 || ORIG_REF_NAME==MarsZX2_auto_pc_8} -quiet] -quiet

# XDC: bd/MarsZX2/ip/MarsZX2_axi_vdma_0_0_2/MarsZX2_axi_vdma_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MarsZX2_axi_vdma_0_0 || ORIG_REF_NAME==MarsZX2_axi_vdma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/MarsZX2/ip/MarsZX2_axi_vdma_0_0_2/MarsZX2_axi_vdma_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MarsZX2_axi_vdma_0_0 || ORIG_REF_NAME==MarsZX2_axi_vdma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/MarsZX2/ip/MarsZX2_axi_vdma_0_0_2/MarsZX2_axi_vdma_0_0_ooc.xdc

# XDC: bd/MarsZX2/ip/MarsZX2_clk_wiz_1_0/MarsZX2_clk_wiz_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MarsZX2_clk_wiz_1_0 || ORIG_REF_NAME==MarsZX2_clk_wiz_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/MarsZX2/ip/MarsZX2_clk_wiz_1_0/MarsZX2_clk_wiz_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MarsZX2_clk_wiz_1_0 || ORIG_REF_NAME==MarsZX2_clk_wiz_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/MarsZX2/ip/MarsZX2_clk_wiz_1_0/MarsZX2_clk_wiz_1_0_ooc.xdc

# XDC: bd/MarsZX2/ip/MarsZX2_proc_sys_reset_0_0_2/MarsZX2_proc_sys_reset_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MarsZX2_proc_sys_reset_0_0 || ORIG_REF_NAME==MarsZX2_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/MarsZX2/ip/MarsZX2_proc_sys_reset_0_0_2/MarsZX2_proc_sys_reset_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MarsZX2_proc_sys_reset_0_0 || ORIG_REF_NAME==MarsZX2_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/MarsZX2/ip/MarsZX2_processing_system7_0_0_2/MarsZX2_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MarsZX2_processing_system7_0_0 || ORIG_REF_NAME==MarsZX2_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/MarsZX2/ip/MarsZX2_v_axi4s_vid_out_0_0_2/MarsZX2_v_axi4s_vid_out_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MarsZX2_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==MarsZX2_v_axi4s_vid_out_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/MarsZX2/ip/MarsZX2_clk_wiz_0_0_1/MarsZX2_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MarsZX2_clk_wiz_0_0 || ORIG_REF_NAME==MarsZX2_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/MarsZX2/ip/MarsZX2_clk_wiz_0_0_1/MarsZX2_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MarsZX2_clk_wiz_0_0 || ORIG_REF_NAME==MarsZX2_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/MarsZX2/ip/MarsZX2_clk_wiz_0_0_1/MarsZX2_clk_wiz_0_0_ooc.xdc

# XDC: bd/MarsZX2/ip/MarsZX2_v_tc_0_0_1/MarsZX2_v_tc_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MarsZX2_v_tc_0_0 || ORIG_REF_NAME==MarsZX2_v_tc_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/MarsZX2/ip/MarsZX2_v_tc_0_0_1/MarsZX2_v_tc_0_0_ooc.xdc

# XDC: bd/MarsZX2/ip/MarsZX2_auto_pc_0_2/MarsZX2_auto_pc_0_ooc.xdc

# XDC: bd/MarsZX2/ip/MarsZX2_auto_pc_9/MarsZX2_auto_pc_9_ooc.xdc

# XDC: bd/MarsZX2/ip/MarsZX2_auto_pc_1_2/MarsZX2_auto_pc_1_ooc.xdc

# XDC: bd/MarsZX2/ip/MarsZX2_auto_pc_2_2/MarsZX2_auto_pc_2_ooc.xdc

# XDC: bd/MarsZX2/ip/MarsZX2_auto_pc_3_2/MarsZX2_auto_pc_3_ooc.xdc

# XDC: bd/MarsZX2/ip/MarsZX2_auto_pc_4_2/MarsZX2_auto_pc_4_ooc.xdc

# XDC: bd/MarsZX2/ip/MarsZX2_auto_pc_5_2/MarsZX2_auto_pc_5_ooc.xdc

# XDC: bd/MarsZX2/ip/MarsZX2_auto_pc_6_2/MarsZX2_auto_pc_6_ooc.xdc

# XDC: bd/MarsZX2/ip/MarsZX2_auto_pc_7_2/MarsZX2_auto_pc_7_ooc.xdc

# XDC: bd/MarsZX2/ip/MarsZX2_auto_pc_8_2/MarsZX2_auto_pc_8_ooc.xdc

# XDC: bd/MarsZX2/MarsZX2_ooc.xdc
