# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 2
create_project -in_memory -part xc7z010clg400-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /mnt/sda1/home/mortega/Proyectos/H2108/Firmware/H2108-CSM/PL3232/PL3232/PL3232.cache/wt [current_project]
set_property parent.project_path /mnt/sda1/home/mortega/Proyectos/H2108/Firmware/H2108-CSM/PL3232/PL3232/PL3232.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_repo_paths /mnt/sda1/home/mortega/Proyectos/H2108/Firmware/H2108-CSM/PL3232/ip_repo [current_project]
update_ip_catalog
set_property ip_output_repo /mnt/sda1/home/mortega/Proyectos/H2108/Firmware/H2108-CSM/PL3232/PL3232/PL3232.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib /mnt/sda1/home/mortega/Proyectos/H2108/Firmware/H2108-CSM/PL3232/PL3232/PL3232.srcs/sources_1/system_top_h8834h.vhd
add_files /mnt/sda1/home/mortega/Proyectos/H2108/Firmware/H2108-CSM/PL3232/PL3232/PL3232.srcs/sources_1/bd/MarsZX2/MarsZX2.bd
set_property used_in_implementation false [get_files -all /mnt/sda1/home/mortega/Proyectos/H2108/Firmware/H2108-CSM/PL3232/PL3232/PL3232.srcs/sources_1/bd/MarsZX2/ip/MarsZX2_axi_vdma_0_0_2/MarsZX2_axi_vdma_0_0.xdc]
set_property used_in_implementation false [get_files -all /mnt/sda1/home/mortega/Proyectos/H2108/Firmware/H2108-CSM/PL3232/PL3232/PL3232.srcs/sources_1/bd/MarsZX2/ip/MarsZX2_axi_vdma_0_0_2/MarsZX2_axi_vdma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /mnt/sda1/home/mortega/Proyectos/H2108/Firmware/H2108-CSM/PL3232/PL3232/PL3232.srcs/sources_1/bd/MarsZX2/ip/MarsZX2_axi_vdma_0_0_2/MarsZX2_axi_vdma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/sda1/home/mortega/Proyectos/H2108/Firmware/H2108-CSM/PL3232/PL3232/PL3232.srcs/sources_1/bd/MarsZX2/ip/MarsZX2_clk_wiz_1_0/MarsZX2_clk_wiz_1_0_board.xdc]
set_property used_in_implementation false [get_files -all /mnt/sda1/home/mortega/Proyectos/H2108/Firmware/H2108-CSM/PL3232/PL3232/PL3232.srcs/sources_1/bd/MarsZX2/ip/MarsZX2_clk_wiz_1_0/MarsZX2_clk_wiz_1_0.xdc]
set_property used_in_implementation false [get_files -all /mnt/sda1/home/mortega/Proyectos/H2108/Firmware/H2108-CSM/PL3232/PL3232/PL3232.srcs/sources_1/bd/MarsZX2/ip/MarsZX2_clk_wiz_1_0/MarsZX2_clk_wiz_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/sda1/home/mortega/Proyectos/H2108/Firmware/H2108-CSM/PL3232/PL3232/PL3232.srcs/sources_1/bd/MarsZX2/ip/MarsZX2_proc_sys_reset_0_0_2/MarsZX2_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /mnt/sda1/home/mortega/Proyectos/H2108/Firmware/H2108-CSM/PL3232/PL3232/PL3232.srcs/sources_1/bd/MarsZX2/ip/MarsZX2_proc_sys_reset_0_0_2/MarsZX2_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all /mnt/sda1/home/mortega/Proyectos/H2108/Firmware/H2108-CSM/PL3232/PL3232/PL3232.srcs/sources_1/bd/MarsZX2/ip/MarsZX2_processing_system7_0_0_2/MarsZX2_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /mnt/sda1/home/mortega/Proyectos/H2108/Firmware/H2108-CSM/PL3232/PL3232/PL3232.srcs/sources_1/bd/MarsZX2/ip/MarsZX2_v_axi4s_vid_out_0_0_2/MarsZX2_v_axi4s_vid_out_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /mnt/sda1/home/mortega/Proyectos/H2108/Firmware/H2108-CSM/PL3232/PL3232/PL3232.srcs/sources_1/bd/MarsZX2/ip/MarsZX2_clk_wiz_0_0_1/MarsZX2_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /mnt/sda1/home/mortega/Proyectos/H2108/Firmware/H2108-CSM/PL3232/PL3232/PL3232.srcs/sources_1/bd/MarsZX2/ip/MarsZX2_clk_wiz_0_0_1/MarsZX2_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all /mnt/sda1/home/mortega/Proyectos/H2108/Firmware/H2108-CSM/PL3232/PL3232/PL3232.srcs/sources_1/bd/MarsZX2/ip/MarsZX2_clk_wiz_0_0_1/MarsZX2_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/sda1/home/mortega/Proyectos/H2108/Firmware/H2108-CSM/PL3232/PL3232/PL3232.srcs/sources_1/bd/MarsZX2/ip/MarsZX2_v_tc_0_0_1/MarsZX2_v_tc_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /mnt/sda1/home/mortega/Proyectos/H2108/Firmware/H2108-CSM/PL3232/PL3232/PL3232.srcs/sources_1/bd/MarsZX2/ip/MarsZX2_v_tc_0_0_1/MarsZX2_v_tc_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/sda1/home/mortega/Proyectos/H2108/Firmware/H2108-CSM/PL3232/PL3232/PL3232.srcs/sources_1/bd/MarsZX2/ip/MarsZX2_auto_pc_0_2/MarsZX2_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/sda1/home/mortega/Proyectos/H2108/Firmware/H2108-CSM/PL3232/PL3232/PL3232.srcs/sources_1/bd/MarsZX2/ip/MarsZX2_auto_pc_9/MarsZX2_auto_pc_9_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/sda1/home/mortega/Proyectos/H2108/Firmware/H2108-CSM/PL3232/PL3232/PL3232.srcs/sources_1/bd/MarsZX2/ip/MarsZX2_auto_pc_1_2/MarsZX2_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/sda1/home/mortega/Proyectos/H2108/Firmware/H2108-CSM/PL3232/PL3232/PL3232.srcs/sources_1/bd/MarsZX2/ip/MarsZX2_auto_pc_2_2/MarsZX2_auto_pc_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/sda1/home/mortega/Proyectos/H2108/Firmware/H2108-CSM/PL3232/PL3232/PL3232.srcs/sources_1/bd/MarsZX2/ip/MarsZX2_auto_pc_3_2/MarsZX2_auto_pc_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/sda1/home/mortega/Proyectos/H2108/Firmware/H2108-CSM/PL3232/PL3232/PL3232.srcs/sources_1/bd/MarsZX2/ip/MarsZX2_auto_pc_4_2/MarsZX2_auto_pc_4_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/sda1/home/mortega/Proyectos/H2108/Firmware/H2108-CSM/PL3232/PL3232/PL3232.srcs/sources_1/bd/MarsZX2/ip/MarsZX2_auto_pc_5_2/MarsZX2_auto_pc_5_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/sda1/home/mortega/Proyectos/H2108/Firmware/H2108-CSM/PL3232/PL3232/PL3232.srcs/sources_1/bd/MarsZX2/ip/MarsZX2_auto_pc_6_2/MarsZX2_auto_pc_6_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/sda1/home/mortega/Proyectos/H2108/Firmware/H2108-CSM/PL3232/PL3232/PL3232.srcs/sources_1/bd/MarsZX2/ip/MarsZX2_auto_pc_7_2/MarsZX2_auto_pc_7_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/sda1/home/mortega/Proyectos/H2108/Firmware/H2108-CSM/PL3232/PL3232/PL3232.srcs/sources_1/bd/MarsZX2/ip/MarsZX2_auto_pc_8_2/MarsZX2_auto_pc_8_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/sda1/home/mortega/Proyectos/H2108/Firmware/H2108-CSM/PL3232/PL3232/PL3232.srcs/sources_1/bd/MarsZX2/MarsZX2_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /mnt/sda1/home/mortega/Proyectos/H2108/Firmware/H2108-CSM/PL3232/PL3232/PL3232.srcs/constrs_1/new/PB3284.xdc
set_property used_in_implementation false [get_files /mnt/sda1/home/mortega/Proyectos/H2108/Firmware/H2108-CSM/PL3232/PL3232/PL3232.srcs/constrs_1/new/PB3284.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top system_top -part xc7z010clg400-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef system_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file system_top_utilization_synth.rpt -pb system_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
