#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : MarsZX2.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Tue Jun 18 14:04:58 CEST 2024
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved. 
#
# usage: MarsZX2.sh [-help]
# usage: MarsZX2.sh [-lib_map_path]
# usage: MarsZX2.sh [-noclean_files]
# usage: MarsZX2.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'MarsZX2.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip xil_defaultlib xpm generic_baseblocks_v2_1_0 axi_infrastructure_v1_1_0 axi_register_slice_v2_1_19 fifo_generator_v13_2_4 axi_data_fifo_v2_1_18 axi_crossbar_v2_1_20 lib_cdc_v1_0_2 lib_pkg_v1_0_2 lib_fifo_v1_0_13 blk_mem_gen_v8_4_3 lib_bmg_v1_0_12 lib_srl_fifo_v1_0_2 axi_datamover_v5_1_21 axi_vdma_v6_3_7 proc_sys_reset_v5_0_13 axi_vip_v1_1_5 processing_system7_vip_v1_0_7 axi_lite_ipif_v3_0_4 v_tc_v6_1_13 v_vid_in_axi4s_v4_0_9 v_axi4s_vid_out_v4_0_10 xlconcat_v2_1_3 xlconstant_v1_1_6 axi_protocol_converter_v2_1_19 axi_mmu_v2_1_17)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "MarsZX2.sh - Script generated by export_simulation (Vivado v2019.1 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/ec9e/hdl" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/c923" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ip/MarsZX2_processing_system7_0_0_2" +incdir+"/tools/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "/mnt/sda1/tools/Xilinx/Vivado/2019.1/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "/mnt/sda1/tools/Xilinx/Vivado/2019.1/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "/mnt/sda1/tools/Xilinx/Vivado/2019.1/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "/mnt/sda1/tools/Xilinx/Vivado/2019.1/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "/mnt/sda1/tools/Xilinx/Vivado/2019.1/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "/mnt/sda1/tools/Xilinx/Vivado/2019.1/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "/mnt/sda1/tools/Xilinx/Vivado/2019.1/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "/mnt/sda1/tools/Xilinx/Vivado/2019.1/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "/mnt/sda1/tools/Xilinx/Vivado/2019.1/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/ec9e/hdl" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/c923" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ip/MarsZX2_processing_system7_0_0_2" +incdir+"/tools/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "/tools/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "/tools/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "/tools/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "/mnt/sda1/tools/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/MarsZX2/ipshared/4783/hdl/SysId_v1_0_S00_AXI.vhd" \
    "$ref_dir/../../../bd/MarsZX2/ipshared/4783/hdl/SysId_v1_0.vhd" \
    "$ref_dir/../../../bd/MarsZX2/ip/MarsZX2_SysId_0_0_2/sim/MarsZX2_SysId_0_0.vhd" \
    "$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/3995/hdl/clock_system.vhd" \
    "$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/3995/hdl/dvi_encoder.vhd" \
    "$ref_dir/../../../bd/MarsZX2/ipshared/3995/src/serdes_ddr.vhd" \
    "$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/3995/hdl/tmds_encoder.vhd" \
    "$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/3995/hdl/Video_IO_2_HDMI_TMDS_v1_0.vhd" \
    "$ref_dir/../../../bd/MarsZX2/ip/MarsZX2_Video_IO_2_HDMI_TMDS_0_0_2/sim/MarsZX2_Video_IO_2_HDMI_TMDS_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/ec9e/hdl" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/c923" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ip/MarsZX2_processing_system7_0_0_2" +incdir+"/tools/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/ec9e/hdl" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/c923" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ip/MarsZX2_processing_system7_0_0_2" +incdir+"/tools/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_19 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/ec9e/hdl" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/c923" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ip/MarsZX2_processing_system7_0_0_2" +incdir+"/tools/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/4d88/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work fifo_generator_v13_2_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/ec9e/hdl" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/c923" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ip/MarsZX2_processing_system7_0_0_2" +incdir+"/tools/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/1f5a/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_4 $vhdlan_opts \
    "$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/1f5a/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/ec9e/hdl" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/c923" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ip/MarsZX2_processing_system7_0_0_2" +incdir+"/tools/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/1f5a/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_18 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/ec9e/hdl" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/c923" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ip/MarsZX2_processing_system7_0_0_2" +incdir+"/tools/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/5b9c/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_20 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/ec9e/hdl" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/c923" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ip/MarsZX2_processing_system7_0_0_2" +incdir+"/tools/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/ace7/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/ec9e/hdl" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/c923" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ip/MarsZX2_processing_system7_0_0_2" +incdir+"/tools/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/MarsZX2/ip/MarsZX2_xbar_0_2/sim/MarsZX2_xbar_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_fifo_v1_0_13 $vhdlan_opts \
    "$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/4dac/hdl/lib_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work blk_mem_gen_v8_4_3 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/ec9e/hdl" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/c923" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ip/MarsZX2_processing_system7_0_0_2" +incdir+"/tools/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/c001/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_bmg_v1_0_12 $vhdlan_opts \
    "$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/7268/hdl/lib_bmg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_srl_fifo_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_datamover_v5_1_21 $vhdlan_opts \
    "$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/e644/hdl/axi_datamover_v5_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_vdma_v6_3_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/ec9e/hdl" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/c923" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ip/MarsZX2_processing_system7_0_0_2" +incdir+"/tools/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/ec9e/hdl/axi_vdma_v6_3_rfs.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_vdma_v6_3_7 $vhdlan_opts \
    "$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/ec9e/hdl/axi_vdma_v6_3_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/MarsZX2/ip/MarsZX2_axi_vdma_0_0_2/sim/MarsZX2_axi_vdma_0_0.vhd" \
    "$ref_dir/../../../bd/MarsZX2/ipshared/4908/src/axis_fb_conv_v1_0.vhd" \
    "$ref_dir/../../../bd/MarsZX2/ip/MarsZX2_axis_fb_conv_0_0_2/sim/MarsZX2_axis_fb_conv_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/ec9e/hdl" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/c923" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ip/MarsZX2_processing_system7_0_0_2" +incdir+"/tools/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/MarsZX2/ip/MarsZX2_clk_wiz_1_0/MarsZX2_clk_wiz_1_0_clk_wiz.v" \
    "$ref_dir/../../../bd/MarsZX2/ip/MarsZX2_clk_wiz_1_0/MarsZX2_clk_wiz_1_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/MarsZX2/ip/MarsZX2_proc_sys_reset_0_0_2/sim/MarsZX2_proc_sys_reset_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_vip_v1_1_5 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/ec9e/hdl" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/c923" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ip/MarsZX2_processing_system7_0_0_2" +incdir+"/tools/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/d4a8/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work processing_system7_vip_v1_0_7 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/ec9e/hdl" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/c923" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ip/MarsZX2_processing_system7_0_0_2" +incdir+"/tools/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/8c62/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/ec9e/hdl" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/c923" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ip/MarsZX2_processing_system7_0_0_2" +incdir+"/tools/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/MarsZX2/ip/MarsZX2_processing_system7_0_0_2/sim/MarsZX2_processing_system7_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work v_tc_v6_1_13 $vhdlan_opts \
    "$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/a92c/hdl/v_tc_v6_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work v_vid_in_axi4s_v4_0_9 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/ec9e/hdl" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/c923" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ip/MarsZX2_processing_system7_0_0_2" +incdir+"/tools/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/b2aa/hdl/v_vid_in_axi4s_v4_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work v_axi4s_vid_out_v4_0_10 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/ec9e/hdl" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/c923" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ip/MarsZX2_processing_system7_0_0_2" +incdir+"/tools/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/a87e/hdl/v_axi4s_vid_out_v4_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/ec9e/hdl" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/c923" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ip/MarsZX2_processing_system7_0_0_2" +incdir+"/tools/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/MarsZX2/ip/MarsZX2_v_axi4s_vid_out_0_0_2/sim/MarsZX2_v_axi4s_vid_out_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconcat_v2_1_3 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/ec9e/hdl" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/c923" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ip/MarsZX2_processing_system7_0_0_2" +incdir+"/tools/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/442e/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/ec9e/hdl" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/c923" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ip/MarsZX2_processing_system7_0_0_2" +incdir+"/tools/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/MarsZX2/ip/MarsZX2_xlconcat_0_0_2/sim/MarsZX2_xlconcat_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconstant_v1_1_6 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/ec9e/hdl" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/c923" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ip/MarsZX2_processing_system7_0_0_2" +incdir+"/tools/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/66e7/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/ec9e/hdl" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/c923" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ip/MarsZX2_processing_system7_0_0_2" +incdir+"/tools/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/MarsZX2/ip/MarsZX2_xlconstant0_1_0_2/sim/MarsZX2_xlconstant0_1_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/MarsZX2/ipshared/f14f/hdl/hwclock_v1_0_S00_AXI.vhd" \
    "$ref_dir/../../../bd/MarsZX2/ipshared/f14f/hdl/hwclock_v1_0.vhd" \
    "$ref_dir/../../../bd/MarsZX2/ip/MarsZX2_hwclock_0_0_2/sim/MarsZX2_hwclock_0_0.vhd" \
    "$ref_dir/../../../bd/MarsZX2/ipshared/15fd/src/ltc2358_pkg.vhd" \
    "$ref_dir/../../../bd/MarsZX2/ipshared/15fd/hdl/ltc2358_v1_0_S00_AXI.vhd" \
    "$ref_dir/../../../bd/MarsZX2/ipshared/15fd/src/ltc2358clx.vhd" \
    "$ref_dir/../../../bd/MarsZX2/ipshared/15fd/hdl/ltc2358_v1_0.vhd" \
    "$ref_dir/../../../bd/MarsZX2/ip/MarsZX2_ltc2358_0_0_2/sim/MarsZX2_ltc2358_0_0.vhd" \
    "$ref_dir/../../../bd/MarsZX2/ipshared/0c34/hdl/csm_sim_v1_0_S00_AXI.vhd" \
    "$ref_dir/../../../bd/MarsZX2/ipshared/0c34/src/sadm_det_csm.vhd" \
    "$ref_dir/../../../bd/MarsZX2/ipshared/0c34/hdl/csm_sim_v1_0.vhd" \
    "$ref_dir/../../../bd/MarsZX2/ip/MarsZX2_csm_sim_0_0_2/sim/MarsZX2_csm_sim_0_0.vhd" \
    "$ref_dir/../../../bd/MarsZX2/ipshared/7eeb/hdl/lld_load_v1_0_S00_AXI.vhd" \
    "$ref_dir/../../../bd/MarsZX2/ipshared/7eeb/hdl/lld_load_v1_0.vhd" \
    "$ref_dir/../../../bd/MarsZX2/ip/MarsZX2_lld_load_0_0_2/sim/MarsZX2_lld_load_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/ec9e/hdl" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/c923" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ip/MarsZX2_processing_system7_0_0_2" +incdir+"/tools/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/MarsZX2/ip/MarsZX2_clk_wiz_0_0_1/MarsZX2_clk_wiz_0_0_clk_wiz.v" \
    "$ref_dir/../../../bd/MarsZX2/ip/MarsZX2_clk_wiz_0_0_1/MarsZX2_clk_wiz_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/MarsZX2/ip/MarsZX2_v_tc_0_0_1/sim/MarsZX2_v_tc_0_0.vhd" \
    "$ref_dir/../../../bd/MarsZX2/ipshared/e4b5/hdl/fan_pwm_v1_0_S00_AXI.vhd" \
    "$ref_dir/../../../bd/MarsZX2/ipshared/e4b5/hdl/fan_pwm_v1_0.vhd" \
    "$ref_dir/../../../bd/MarsZX2/ip/MarsZX2_fan_pwm_0_0/sim/MarsZX2_fan_pwm_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_protocol_converter_v2_1_19 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/ec9e/hdl" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/c923" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ip/MarsZX2_processing_system7_0_0_2" +incdir+"/tools/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/c83a/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/ec9e/hdl" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/c923" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ip/MarsZX2_processing_system7_0_0_2" +incdir+"/tools/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/MarsZX2/ip/MarsZX2_auto_pc_0_2/sim/MarsZX2_auto_pc_0.v" \
    "$ref_dir/../../../bd/MarsZX2/ip/MarsZX2_auto_pc_9/sim/MarsZX2_auto_pc_9.v" \
    "$ref_dir/../../../bd/MarsZX2/ip/MarsZX2_auto_pc_1_2/sim/MarsZX2_auto_pc_1.v" \
    "$ref_dir/../../../bd/MarsZX2/ip/MarsZX2_auto_pc_2_2/sim/MarsZX2_auto_pc_2.v" \
    "$ref_dir/../../../bd/MarsZX2/ip/MarsZX2_auto_pc_3_2/sim/MarsZX2_auto_pc_3.v" \
    "$ref_dir/../../../bd/MarsZX2/ip/MarsZX2_auto_pc_4_2/sim/MarsZX2_auto_pc_4.v" \
    "$ref_dir/../../../bd/MarsZX2/ip/MarsZX2_auto_pc_5_2/sim/MarsZX2_auto_pc_5.v" \
    "$ref_dir/../../../bd/MarsZX2/ip/MarsZX2_auto_pc_6_2/sim/MarsZX2_auto_pc_6.v" \
    "$ref_dir/../../../bd/MarsZX2/ip/MarsZX2_auto_pc_7_2/sim/MarsZX2_auto_pc_7.v" \
    "$ref_dir/../../../bd/MarsZX2/ip/MarsZX2_auto_pc_8_2/sim/MarsZX2_auto_pc_8.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_mmu_v2_1_17 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/ec9e/hdl" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/c923" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ip/MarsZX2_processing_system7_0_0_2" +incdir+"/tools/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/b5b8/hdl/axi_mmu_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/ec9e/hdl" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/c923" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../PL3232.srcs/sources_1/bd/MarsZX2/ip/MarsZX2_processing_system7_0_0_2" +incdir+"/tools/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/MarsZX2/ip/MarsZX2_s00_mmu_0/sim/MarsZX2_s00_mmu_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/MarsZX2/sim/MarsZX2.vhd" \
  2>&1 | tee -a vhdlan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.MarsZX2 xil_defaultlib.glbl -o MarsZX2_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./MarsZX2_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./MarsZX2.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  else
    lib_map_path="/mnt/sda1/home/mortega/Proyectos/H2108/Firmware/H2108-CSM/PL3232/PL3232/PL3232.cache/compile_simlib/vcs"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key MarsZX2_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc MarsZX2_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./MarsZX2.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: MarsZX2.sh [-help]\n\
Usage: MarsZX2.sh [-lib_map_path]\n\
Usage: MarsZX2.sh [-reset_run]\n\
Usage: MarsZX2.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
